# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
    - Emulator
    - EmulatorInfo
    - Error
    - Optimization
    - DropRecord
    General:
    - Retirement
    - OneClickRetire
    - Enhance
    - OldRetire
    Restart:
    - Scheduler

# ==================== DailyMission ====================

DailyMission:
  menu: 'list'
  page: 'setting'
  tasks:
    Daily:
    - Scheduler
    - Daily
